src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Contract_Date__c</fullName>
        <label>Last Contract Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.INACTIVE_CONTACT__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Training_Event__c.object
<CustomObject>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From Opportunity Record</inlineHelpText>
        <label>Decision Maker</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <label>Training Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LastContractDateFunctionalityHandlerTest.cls
@isTest
private class LastContractDateFunctionalityHandlerTest {
	
	@isTest static void insertLastContract() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c = new Contact(LastName='test 1',Last_Contract_Date__c = null);
		insert c;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c.Id);
		insert te;

        Contact cResult = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c.Id];
        system.assertEquals(Date.today(), cResult.Last_Contract_Date__c);
		//system.assertEquals(true,te != null);

	}
	
	@isTest static void updateLastContract() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c = new Contact(LastName='test 1',Last_Contract_Date__c = Date.today().addDays(-3));
		insert c;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c.Id);
		insert te;

		te.Name='223';
		update te;

        Contact cResult = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c.Id];
        system.assertEquals(Date.today(), cResult.Last_Contract_Date__c);
		//system.assertEquals(true,te != null);
	}
	@isTest static void newTrainingEventContactWithNullDate() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c = new Contact(LastName='test 1',Last_Contract_Date__c = null);
		insert c;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c.Id);
		insert te;

        Contact cResult = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c.Id];
		system.assertEquals(Date.today(), cResult.Last_Contract_Date__c);
	}
	
	@isTest static void newTrainingEventContactWithDate() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c = new Contact(LastName='test 1',Last_Contract_Date__c = Date.today().addDays(-10));
		insert c;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c.Id);
		insert te;
		
        Contact cResult = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c.Id];
		system.assertEquals(Date.today(), cResult.Last_Contract_Date__c);
	}

	@isTest static void updateTrainingEventContactWithNoDate() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c1 = new Contact(LastName='test 1',Last_Contract_Date__c = null);
		insert c1;

		Contact c2 = new Contact(LastName='test 1',Last_Contract_Date__c = null);
		insert c2;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c1.Id);
		insert te;

		te.Decision_Maker__c = c2.Id;
		update te;

        Contact cResult1 = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c1.Id];
        Contact cResult2 = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c2.Id];
		system.assertEquals(Date.today(), cResult1.Last_Contract_Date__c); // This should pass because of insert
		system.assertEquals(Date.today(), cResult2.Last_Contract_Date__c); // This should pass because of update
	}

	@isTest static void updateTrainingEventContactWithDate() {
		Opportunity opp = new Opportunity(Name='Test 10',StageName='Aaa',CloseDate=Date.today());
		insert opp;

		Contact c1 = new Contact(LastName='test 1',Last_Contract_Date__c = Date.today().addDays(-10));
		insert c1;

		Contact c2 = new Contact(LastName='test 1',Last_Contract_Date__c = Date.today().addDays(-10));
		insert c2;

		Training_Event__c te = new Training_Event__c(Opportunity__c = opp.Id,Name='test',Decision_Maker__c = c1.Id);
		insert te;

		te.Decision_Maker__c = c2.Id;
		update te;

		Contact cResult1 = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c1.Id];
        Contact cResult2 = [SELECT Id, Last_Contract_Date__c FROM Contact WHERE Id = :c2.Id];
		system.assertEquals(Date.today(), cResult1.Last_Contract_Date__c); // This should pass because of insert
		system.assertEquals(Date.today(), cResult2.Last_Contract_Date__c); // This should pass because of update
	}
}