src/objects/Post_Survey__c.object
<CustomObject>
    <description>The Post Event Survey captures information from the client about their impression of the event.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Event Post Surveys</relationshipLabel>
        <relationshipName>Training_Event_Post_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Event Post Surveys (Trainer)</relationshipLabel>
        <relationshipName>Training_Event_Post_Surveys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Event__c</fullName>
        <description>Each Tailoring Survey should be related to an existing Training Event.</description>
        <inlineHelpText>Each Tailoring Survey should be related to an existing Training Event.</inlineHelpText>
        <label>Training Event</label>
        <referenceTo>Training_Event__c</referenceTo>
        <relationshipName>Training_Event_Tailoring_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Training Event Post Survey</label>
    <nameField>
        <label>Survey Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Event Post Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training_Event__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Events3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trainer_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Actual Trainer assigned to this event.</inlineHelpText>
        <label>Trainer Assigned</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Trainer Contacts</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>equals</operation>
                <value>SkillPath Trainers</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Events (Trainer - Actual)</relationshipLabel>
        <relationshipName>Training_Events4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <label>Training Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PostSurveyTriggerTest.cls
@isTest
public class PostSurveyTriggerTest {
    
    static testMethod void testBeforeInsert() {

        Account a = new Account(Name = 'Test Account');
        insert a;

        Contact c = new Contact(LastName = 'Test Contact', AccountId = a.Id);
        insert c;

        Opportunity o = new Opportunity(Name = 'Test Opp', AccountId = a.Id, StageName = 'Closed Won', CloseDate = Date.newInstance(2015,1,1));
        insert o;

        Training_Event__c te = new Training_Event__c(Name = 'Test TE', Opportunity__c = o.Id, Trainer_Assigned__c = c.Id, Account__c = a.Id);
        insert te;

        Post_Survey__c ps = new Post_Survey__c(Name = 'Test TEPS', Training_Event__c = te.Id);
        insert ps;

        Post_Survey__c psCommitted = [SELECT Id, Trainer__c, Account__c FROM Post_Survey__c WHERE Id = :ps.Id];

        System.assertEquals(c.Id, psCommitted.Trainer__c);
        System.assertEquals(a.Id, psCommitted.Account__c);

    }
    
}